### PR TITLE
Add ui

### PR DESCRIPTION
**Pull request by hasauino**
Implements suggestion 2 proposed in this [issue](https://github.com/IbraheemTuffaha/sonix.ai-assistant/issues/6)

Adds a user interface from which the user can choose:

- Count update method: continuously (like before, on keyup, load, and scroll), or on video play only.
- To enable/disable captions

### CODE REVIEW

**Comment by AliOsm** [comment]
Hello Hasan, the change looks great.

I have one minor comment about the options list, would you prefer to change the second option from "Hide caption" to "Show caption" and flip its functionality, I think it would be a better UX.

**Comment by hasauino** [comment]
@AliOsm I was thinking the same thing, I will do it...
did you try it? did you encounter any errors?

**Comment by AliOsm** [comment]
@hasauino, Yes I tried it and I didn't catch any errors.

**Comment by hasauino** [comment]
I will close this PR, and make a new one based on @Dev-Now  changes

**Pull request closed without merging**
