### PR TITLE
make char count show for paragraphs in view only

### PR DESCRIPTION
**Pull request by Dev-Now**
@hasauino @IbraheemTuffaha 
Salam Alaykum brothers,
I made this update which dramatically improved performance on my 34 min sonix video:
Changes are:
- char count displays only for in view paragraphs. Fixes issue #6.
- reset of realtime char count and caption display

Please review.

### CODE REVIEW

**Comment by hasauino** [comment]
This is great, I will test it now on my computer.
I have a suggestion, why don't we keep the changes I made in this PR #7, I mean if your changes are built on top of my PR (you branch off **add_UI** branch not master), then the user has two options for count update (1-continuous and 2- onplay) both use your method of updating the counts..
Also it gives the user the option to remove captions..

I can also delete my PR and do the changes on top of your branch...

**Comment by hasauino** [comment]
@Dev-Now 
The performance is improved indeed.
There is only this [line](https://github.com/Dev-Now/sonix.ai-assistant/blob/de73122b5f61d1098fdd6ed3ae9760d4ebddf8b8/js/count_characters.js#L46) I think you forgot to remove (consol.log..)

**Comment by Dev-Now** [comment]
True. I forgot to remove it.

**Comment by hasauino** [comment]
As I discussed with you @Dev-Now and @IbraheemTuffaha 
I think we better release this PR (after your review).
Then, I will add the UI and this might be the next release.

**Pull request merged**
